/*****************************************************************************
* | File      	:   Web_CSS.c
* | Author      :   Waveshare team
* | Function    :	  send html string
* |	This version:   V1.0
* | Date        :   2019-08-26
* | Info        :
*----------------
******************************************************************************/
extern  WebServer server;
void Web_SendCSS()
{
    server.send(200, "text/css",
                "body {\r\n"
                "    margin: 0px;\r\n"
                "    padding: 0px;\r\n"
                "}\r\n"
                ".large {\r\n"
                "    width: 100vw;\r\n"
                "    height: 100vh;\r\n"
                "}\r\n"
                ".large .Menu {\r\n"
                "    float: left;\r\n"
                "    width: 12vw;\r\n"
                "    min-width: 250px;\r\n"
                "    height: 100%;\r\n"
                "    color: #FFFFFF;\r\n"
                "    background-color: #292929;\r\n"
                "    box-shadow: 0px 0px 10px #313131;\r\n"
                "}\r\n"
                ".large .SubMenu {\r\n"
                "    float: left;\r\n"
                "    width: 8vw;\r\n"
                "    min-width: 200px;\r\n"
                "    height: 100%;\r\n"
                "    display: none;\r\n"
                "    color: #458f00;\r\n"
                "    background-color: #3D3D3D;\r\n"
                "    box-shadow: 0px 0px 10px #515151;\r\n"
                "}\r\n"
                ".large .maincontent {\r\n"
                "    height: 100vh;\r\n"
                "    overflow-x: hidden;\r\n"
                "    line-height: 30px;\r\n"
                "    background: #EEEEEE;\r\n"
                "}\r\n"
                ".large .maincontent::-webkit-scrollbar {\r\n"
                "    display: none;\r\n"
                "}\r\n"
                ".Menu .Item {\r\n"
                "    width: 80%;\r\n"
                "    margin: auto;\r\n"
                "}\r\n"
                ".Menu .Item .ch-home {\r\n"
                "    font-size: 22px;\r\n"
                "    font-style: normal;\r\n"
                "    font-weight: 600;\r\n"
                "    text-decoration: none;\r\n"
                "    color: #079aff;\r\n"
                "}\r\n"
                ".Menu .Item .en-home {\r\n"
                "    font-size: 20px;\r\n"
                "    font-style: normal;\r\n"
                "    text-decoration: none;\r\n"
                "    color: green;\r\n"
                "}\r\n"
                ".Menu .Nav {\r\n"
                "    min-width: 200px;\r\n"
                "    width: 80%;\r\n"
                "    margin: 0 auto;\r\n"
                "    padding: 10px 0px;\r\n"
                "    display: block;\r\n"
                "}\r\n"
                ".Menu .firstDeviceIP {\r\n"
                "    min-width: 230px;\r\n"
                "    font-size: 18px;\r\n"
                "    color: aqua;\r\n"
                "}\r\n"
                ".Menu .firstDeviceIPinput {\r\n"
                "    font-size: 18px;\r\n"
                "    color: aqua;\r\n"
                "    width: 130px;\r\n"
                "    background: #292929;\r\n"
                "    border: 0px;\r\n"
                "}\r\n"
                ".Menu .firstNav {\r\n"
                "    margin: 0 auto;\r\n"
                "    padding: 10px 0px;\r\n"
                "    display: block;\r\n"
                "    text-decoration: none;\r\n"
                "}\r\n"
                ".Menu .Nav .firstNav {\r\n"
                "    display: inline-block;\r\n"
                "    font-size: 20px;\r\n"
                "    text-shadow: 0px 0px 3px #EEEEEE;\r\n"
                "}\r\n"
                ".Menu .Nav .firstNav:hover {\r\n"
                "    background-color: #3D3D3D;\r\n"
                "    cursor: pointer;\r\n"
                "}\r\n"
                ".Menu .showimage_button, .Menu .uploadimage_button {\r\n"
                "    width: 80%;\r\n"
                "    margin: 10px auto;\r\n"
                "    height: 50px;\r\n"
                "    font-size: 16px;\r\n"
                "    background-color: #4CAF50;\r\n"
                "    border: none;\r\n"
                "    display: block;\r\n"
                "    color: white;\r\n"
                "    border-radius: 12px;\r\n"
                "}\r\n"
                ".Menu .showimage_button {\r\n"
                "    background-color: #2712FF;\r\n"
                "}\r\n"
                ".showimage_button:hover {\r\n"
                "    background-color: #e5e5e5;\r\n"
                "    color: #2712FF;\r\n"
                "}\r\n"
                ".uploadimage_button:hover {\r\n"
                "    background-color: #e5e5e5;\r\n"
                "    color: #4CAF50;\r\n"
                "}\r\n"
                ".SubMenu .DrawingDrop {\r\n"
                "    top: 2%;\r\n"
                "    display: none;\r\n"
                "    margin: 0 auto;\r\n"
                "    position: relative;\r\n"
                "    padding: 10px;\r\n"
                "    padding-top: 6px;\r\n"
                "    padding-bottom: 6px;\r\n"
                "    left: 1%;\r\n"
                "}\r\n"
                ".SubMenu .DrawingDrop .DrawingNav {\r\n"
                "    text-align: left;\r\n"
                "    line-height: 30px;\r\n"
                "    font-size: 20px;\r\n"
                "}\r\n"
                ".SubMenu .DrawingNav:hover {\r\n"
                "    background-color: #458f00;\r\n"
                "    color: #3D3D3D;\r\n"
                "    cursor: pointer;\r\n"
                "}\r\n"
                "/*页眉主页页脚*/\r\n"
                ".maincontent .header {\r\n"
                "    background: #c0ffb9;\r\n"
                "    color: #7976f2;\r\n"
                "    height: 70px;\r\n"
                "}\r\n"
                ".header .epdname {\r\n"
                "    text-align: center;\r\n"
                "    font-size: 30px;\r\n"
                "    font-weight: 500;\r\n"
                "    width: 400px;\r\n"
                "    margin: auto;\r\n"
                "    padding-top: 5px;\r\n"
                "    padding-bottom: 5px;\r\n"
                "}\r\n"
                ".header .epdpixelandcolor {\r\n"
                "    text-align: center;\r\n"
                "    font-size: 20px;\r\n"
                "    width: 400px;\r\n"
                "    margin: auto;\r\n"
                "}\r\n"
                ".maincontent .page {\r\n"
                "    background: #e5e5e5;\r\n"
                "}\r\n"
                ".maincontent .footer {\r\n"
                "    background: #c0ffb9;\r\n"
                "    color: #7976f2;\r\n"
                "}\r\n"
                ".footer .footername {\r\n"
                "    text-align: center;\r\n"
                "    font-size: 15px;\r\n"
                "    font-weight: 500;\r\n"
                "    width: 400px;\r\n"
                "    margin: auto;\r\n"
                "    padding-top: 5px;\r\n"
                "    padding-bottom: 5px;\r\n"
                "}\r\n"
                "/*******************按键+通用组件*******************/\r\n"
                ".maincontent .DrawName {\r\n"
                "    font-size: 21px;\r\n"
                "    padding-left: 8px;\r\n"
                "}\r\n"
                ".Draw-button {\r\n"
                "    font-size: 16px;\r\n"
                "    border: none;\r\n"
                "    color: white;\r\n"
                "    padding: 8px 18px;\r\n"
                "    text-align: center;\r\n"
                "    text-decoration: none;\r\n"
                "    display: inline-block;\r\n"
                "    margin: 4px 2px;\r\n"
                "    cursor: pointer;\r\n"
                "    border-radius: 12px;\r\n"
                "}\r\n"
                ".Draw-button1 {\r\n"
                "    background-color: #4CAF50;\r\n"
                "}\r\n"
                ".Draw-button2 {\r\n"
                "    display: none;\r\n"
                "    background-color: #f44336;\r\n"
                "}\r\n"
                ".Draw-button3 {\r\n"
                "    background-color: #555555;\r\n"
                "}\r\n"
                ".Draw-button1:hover {\r\n"
                "    background-color: #e5e5e5;\r\n"
                "    color: #4CAF50;\r\n"
                "}\r\n"
                ".Draw-button2:hover {\r\n"
                "    background-color: #e5e5e5;\r\n"
                "    color: #f44336;\r\n"
                "}\r\n"
                ".Draw-button3:hover {\r\n"
                "    background-color: #e5e5e5;\r\n"
                "    color: #555555;\r\n"
                "}\r\n"
                ".maincontent table {\r\n"
                "    padding-left: 5px;\r\n"
                "    width: 100px;\r\n"
                "}\r\n"
                ".DrawNav {\r\n"
                "    text-align: center;\r\n"
                "}\r\n"
                ".DrawNav th {\r\n"
                "    font-size: 1.1em;\r\n"
                "    padding-top: 5px;\r\n"
                "    padding-bottom: 4px;\r\n"
                "    background-color: rgb(35, 36, 34);\r\n"
                "    color: #ffffff;\r\n"
                "}\r\n"
                ".DrawNav td {\r\n"
                "    font-size: 1em;\r\n"
                "    border: 1px solid #8b8792;\r\n"
                "    padding: 3px 7px 2px 7px;\r\n"
                "}\r\n"
                ".DrawNav input {\r\n"
                "    width: 100px;\r\n"
                "    text-align: center;\r\n"
                "}\r\n"
                ".DrawNav button {\r\n"
                "    width: 135px;\r\n"
                "    text-align: center;\r\n"
                "}\r\n"
                ".image-button {\r\n"
                "    position: relative;\r\n"
                "    width: 130px;\r\n"
                "    height: 30px;\r\n"
                "    border-radius: 5px;\r\n"
                "    background-color: rgb(124, 245, 186);\r\n"
                "    color: #333333;\r\n"
                "    font-size: 14px;\r\n"
                "    text-align: center;\r\n"
                "    overflow: hidden;\r\n"
                "}\r\n"
                ".image-button span {\r\n"
                "    text-overflow: ellipsis;\r\n"
                "    white-space: nowrap;\r\n"
                "    overflow: hidden;\r\n"
                "}\r\n"
                ".image-button:hover {\r\n"
                "    font-size: 15px;\r\n"
                "    border-color: rgb(39, 226, 81);\r\n"
                "}\r\n"
                ".image-button input[type=\'file\'] {\r\n"
                "    position: absolute;\r\n"
                "    opacity: 0;/*  隐藏浏览 */\r\n"
                "}\r\n"
                "/****************************************/\r\n"
                ".pagewidth {\r\n"
                "    margin: auto;\r\n"
                "    min-width: 1000px;\r\n"
                "}\r\n"
                ".maincontent .DrawPoint, .maincontent .DrawLine, .maincontent .DrawRectangle, .maincontent .DrawCircle, .maincontent .DrawString, .maincontent .ShowPic {\r\n"
                "    display: none;\r\n"
                "    background: #f7c698;\r\n"
                "}\r\n"
                ".DrawCanvas, .DrawCanvas2 {\r\n"
                "    border: 2px dashed green;\r\n"
                "    border-radius: 8px;\r\n"
                "    background: rgb(255, 255, 255);\r\n"
                "    background-repeat: repeat;\r\n"
                "    background-repeat: no-repeat;\r\n"
                "    position: inherit;\r\n"
                "}\r\n"
                ".DrawCanvas .DrawCanvastext {\r\n"
                "    margin: auto;\r\n"
                "    text-align: center;\r\n"
                "    font-size: larger;\r\n"
                "    position: relative;\r\n"
                "    line-height: 0vh;\r\n"
                "    top: 50%;\r\n"
                "}"
               );
}
