/*****************************************************************************
* | File      	:   Web_Scripts.c
* | Author      :   Waveshare team
* | Function    :	  send Scripts string
* |	This version:   V1.0
* | Date        :   2019-08-26
* | Info        :
*----------------
******************************************************************************/
extern WebServer server;
void Web_SendJS_A()
{
    server.send(200, "text/javascript",
                "var epdnum;\r\n"
                "var epdArr = [\r\n"
                "    [\'1.54inch e-paper\',       200, 200, 0, 0],\r\n"
                "    [\'1.54inch e-paper V2\',    200, 200, 0, 0],\r\n"
                "    [\'1.54inch e-paper (B)\',   200, 200, 1, 3],\r\n"
                "    [\'1.54inch e-Paper (C)\',   152, 152, 2, 5],\r\n"
                "    [\'2.13inch e-Paper\',       250, 122, 0, 0],\r\n"
                "    [\'2.13inch e-Paper V2\',    250, 122, 0, 0],\r\n"
                "    [\'2.13inch e-Paper (B)\',   212, 104, 1, 1],\r\n"
                "    [\'2.13inch e-Paper (C)\',   212, 104, 2, 5],\r\n"
                "    [\'2.13inch e-Paper (D)\',   212, 104, 0, 0],\r\n"
                "    [\'2.7inch e-Paper\',        264, 176, 0, 0],\r\n"
                "    [\'2.7inch e-Paper (B)\',    264, 176, 1, 1],\r\n"
                "    [\'2.9inch e-Paper\',        296, 128, 0, 0],\r\n"
                "    [\'2.9inch e-Paper (B)\',    296, 128, 1, 1],\r\n"
                "    [\'2.9inch e-Paper (C)\',    296, 128, 2, 5],\r\n"
                "    [\'2.9inch e-Paper (D)\',    296, 128, 0, 0],\r\n"
                "    [\'4.2inch e-Paper\',        400, 300, 0, 0],\r\n"
                "    [\'4.2inch e-Paper (B)\',    400, 300, 1, 1],\r\n"
                "    [\'4.2inch e-Paper (C)\',    400, 300, 2, 5],\r\n"
                "    [\'5.83inch e-Paper\',       600, 448, 0, 0],\r\n"
                "    [\'5.83inch e-Paper (B)\',   600, 448, 1, 1],\r\n"
                "    [\'5.83inch e-Paper (C)\',   600, 448, 2, 5],\r\n"
                "    [\'7.5inch e-Paper\',        640, 384, 0, 0],\r\n"
                "    [\'7.5inch e-Paper (B)\',    640, 384, 1, 1],\r\n"
                "    [\'7.5inch e-Paper (C)\',    640, 384, 2, 5],\r\n"
                "    [\'7.5inch e-Paper V2\',     800, 480, 0, 0],\r\n"
                "    [\'7.5inch e-Paper (B) V2\', 800, 480, 1, 1],\r\n"
                "    [\'7.5inch e-Paper (C) V2\', 800, 480, 2, 5],\r\n"
                "    [\'12.48inch e-Paper\',     1304, 984, 0, 0],\r\n"
                "    [\'12.48inch e-Paper (B)\', 1304, 984, 1, 1],\r\n"
                "    [\'12.48inch e-Paper (C)\', 1304, 984, 2, 5]\r\n"
                "];\r\n"
                "var palArr = [\r\n"
                "    [[0, 0, 0], [255, 255, 255]],\r\n"
                "    [[0, 0, 0], [255, 255, 255], [255, 0, 0]],\r\n"
                "    [[0, 0, 0], [255, 255, 255], [127, 127, 127]],\r\n"
                "    [[0, 0, 0], [255, 255, 255], [127, 127, 127], [127, 0, 0]],\r\n"
                "    [[0, 0, 0], [255, 255, 255]],\r\n"
                "    [[0, 0, 0], [255, 255, 255], [220, 180, 0]]\r\n"
                "];\r\n"
                "var DrawIfShow = [\r\n"
                "    [\'DrawPoint\', 0],\r\n"
                "    [\'DrawLine\', 0],\r\n"
                "    [\'DrawRectangle\', 0],\r\n"
                "    [\'DrawCircle\', 0],\r\n"
                "    [\'DrawString\', 0],\r\n"
                "    [\'DrawChinese\', 0],\r\n"
                "    [\'ShowPicture\', 0]\r\n"
                "];\r\n"
                "/**/\r\n"
                "function indexOf(arr, item) {\r\n"
                "    for (var i = 0; i < arr.length; i++) {\r\n"
                "        if (arr[i][0] === item)\r\n"
                "            return i;\r\n"
                "    }\r\n"
                "}\r\n"
                "function consoledebug(str) {\r\n"
                "    var debug = 1;\r\n"
                "    if (debug) console.log(str);\r\n"
                "}\r\n"
                "var showorhide_flag = 0; // 0:hide,1:show\r\n"
                "function showorhide() {\r\n"
                "    if (showorhide_flag == 0) {\r\n"
                "        consoledebug(\'show\');\r\n"
                "        $(\'.SubMenu\').show();\r\n"
                "        $(\'.DrawingDrop\').show();\r\n"
                "        $(\'.page\').show();\r\n"
                "        $(\'.footer\').show();\r\n"
                "        // showorhide_flag = 1;\r\n"
                "    } else {\r\n"
                "        consoledebug(\'hide\');\r\n"
                "        $(\'.SubMenu\').hide();\r\n"
                "        $(\'.DrawingDrop\').hide();\r\n"
                "        showorhide_flag = 0;\r\n"
                "    }\r\n"
                "}\r\n"
                "var ry_color;\r\n"
                "function hasRed(epdnum) {\r\n"
                "    $(\'.show_ry\').css({ \'display\': \'none\'});\r\n"
                "    if(epdArr[epdnum][3] == 1){\r\n"
                "        ry_color = \'RED\';\r\n"
                "    } else{\r\n"
                "        ry_color = \'\';\r\n"
                "    }\r\n"
                "    $(\'.show_ry\').css({ \'display\': epdArr[epdnum][3] == 0 ? \'none\' : \'block\'});\r\n"
                "}\r\n"
                "var canvasWidth, canvasHeight;\r\n"
                "function showmain(epdnum) {\r\n"
                "    consoledebug(epdArr[epdnum][0]);\r\n"
                "    $(\'.epd\').show();\r\n"
                "    $(\'.epdname\').empty();\r\n"
                "    $(\'.epdpixelandcolor\').empty();\r\n"
                "    $(\'.epdname\').prepend(epdArr[epdnum][0]);\r\n"
                "    $(\'.epdpixelandcolor\').prepend(epdArr[epdnum][1] + \' * \' + epdArr[epdnum][2] + \' Pixel \' + \"<span style=\'color: black\'> Black</span> + <span style=\'color: white\'> White</span>\" + (epdArr[epdnum][3] == 0 ? \' \' : (epdArr[epdnum][3] == 1 ? \" +<span style=\'color: red\'> Red</span>\":\" +<span style=\'color: yellow\'> Yellow</span>\")));\r\n"
                "    hasRed(epdnum);\r\n"
                "    pageMinHeight = $(window).height() - $(\'.header\').height() - $(\'.footer\').height();\r\n"
                "    $(\'.page\').css({ \'min-height\': pageMinHeight + \'px\' });\r\n"
                "    canvasWidth = epdArr[epdnum][1] + \'\';\r\n"
                "    canvasHeight = epdArr[epdnum][2] + \'\';\r\n"
                "    $(\'.pagewidth\').css({\'width\': canvasWidth + \'px\'});\r\n"
                "    $(\'.DrawCanvas\').css({\'width\': canvasWidth + \'px\' ,\'height\': canvasHeight + \'px\' });\r\n"
                "}\r\n"
                "var showDrawCanvas_Flag = 0;\r\n"
                "function showDrawCanvas() {\r\n"
                "    if (showDrawCanvas_Flag == 0) {\r\n"
                "        $(\'.DrawCanvas\').empty();\r\n"
                "        $(\'.DrawCanvas\').append(\"<canvas class=\'epdCanvas\' id=\'epdCanvas\' width=\" + canvasWidth + \' height=\' + canvasHeight + \'</canvas>\');\r\n"
                "        showDrawCanvas_Flag = 1;\r\n"
                "    }\r\n"
                "}\r\n"
                "$(function () {\r\n"
                "    $(\'.12in48_epd-js\').click(function () {\r\n"
                "        showorhide();\r\n"
                "        epdnum = indexOf(epdArr, \'12.48inch e-Paper\');\r\n"
                "        showmain(epdnum);\r\n"
                "    });\r\n"
                "    $(\'.12in48b_epd-js\').click(function () {\r\n"
                "        showorhide();\r\n"
                "        epdnum = indexOf(epdArr, \'12.48inch e-Paper (B)\');\r\n"
                "        showmain(epdnum);\r\n"
                "    });\r\n"
                "    $(\'.12in48c_epd-js\').click(function () {\r\n"
                "        showorhide();\r\n"
                "        epdnum = indexOf(epdArr, \'12.48inch e-Paper (C)\');\r\n"
                "        showmain(epdnum);\r\n"
                "    });\r\n"
                "    $(\'.DrawPoint-js\').click(function () {\r\n"
                "        consoledebug(\'DrawPoint\');\r\n"
                "        showDrawCanvas();\r\n"
                "        if (DrawIfShow[0][1] == 0) {\r\n"
                "            $(\'.DrawCanvas\').before(\"<div class=\'DrawPoint pagewidth\'><div class=\'DrawName\'>Draw Point <button class=\'Draw-button Draw-button1 DrawPoint_add_click\'>+</button> <button class=\'Draw-button Draw-button2 DrawPoint_del_click\'>-</button> <button class=\'Draw-button Draw-button3 DrawPoint_delall_click\'>delete</button></div><div class=\'Points-father\'><table class=\'Point\'><tr class=\'DrawNav\'><th>Num</th><th>X</th><th>Y</th><th>Color</th><th>Pixel</th></tr><tr class=\'DrawNav\'><td>1</td><td><input type=\'text\' name=\'Point_x\' value=\'0\'></td><td><input type=\'text\' name=\'Point_y valput\' value=\'0\'></td><td><select name=\'Point_Color\'><option value=\'0\'>WHITE</option><option value=\'1\'>BLACK</option><option class=\'show_ry\' value=\'2\'>\"+ ry_color + \"</option></select></td><td><select name=\'Point_Pixel\'><option value=\'1\' selected>1</option><option value=\'2\'>2</option><option value=\'3\'>3</option><option value=\'4\'>4</option><option value=\'5\'>5</option><option value=\'6\'>6</option><option value=\'7\'>7</option><option value=\'8\'>8</option></select></td></tr></table></div></div>\");\r\n"
                "            $(\'.DrawPoint\').show();\r\n"
                "            DrawIfShow[0][1] = 1;\r\n"
                "        }\r\n"
                "    });\r\n"
                "    $(\'.DrawLine-js\').click(function () {\r\n"
                "        consoledebug(\'DrawLine\');\r\n"
                "        showDrawCanvas();\r\n"
                "        if (DrawIfShow[1][1] == 0) {\r\n"
                "            $(\'.DrawCanvas\').before(\"<div class=\'DrawLine pagewidth\'><div class=\'DrawName\'>Draw Line <button class=\'Draw-button Draw-button1 DrawLine_add_click\'>+</button> <button class=\'Draw-button Draw-button2 DrawLine_del_click\'>-</button> <button class=\'Draw-button Draw-button3 DrawLine_delall_click\'>delete</button></div><div class=\'Lines-father\'><table class=\'Line\'><tr class=\'DrawNav\'><th>Num</th><th>Xstart</th><th>Ystart</th><th>Xend</th><th>Yend</th><th>Color</th><th>Width</th><th>Style</th></tr><tr class=\'DrawNav\'><td>1</td><td><input type=\'text\' name=\'Line_x1\' value=\'0\'></td><td><input type=\'text\' name=\'Line_y1\' value=\'0\'></td><td><input type=\'text\' name=\'Line_x2\' value=\'0\'></td><td><input type=\'text\' name=\'Line_y2\' value=\'0\'></td><td><select name=\'Line_Color\'><option value=\'0\'>WHITE</option><option value=\'1\'>BLACK</option><option class=\'show_ry\' value=\'2\'>\"+ ry_color + \"</option></select></td><td><select name=\'Line_Width\'><option value=\'1\' selected>1</option><option value=\'2\'>2</option><option value=\'3\'>3</option><option value=\'4\'>4</option><option value=\'5\'>5</option><option value=\'6\'>6</option><option value=\'7\'>7</option><option value=\'8\'>8</option></select></td><td><select name=\'Line_Style\'><option value=\'1\' selected>SOLID</option><option value=\'2\'>DOTTED</option></select></td></tr></table></div></div>\");\r\n"
                "            $(\'.DrawLine\').show();\r\n"
                "            DrawIfShow[1][1] = 1;\r\n"
                "        }\r\n"
                "    });\r\n"
                "    $(\'.DrawRectangle-js\').click(function () {\r\n"
                "        consoledebug(\'DrawRectangle\');\r\n"
                "        showDrawCanvas();\r\n"
                "        if (DrawIfShow[2][1] == 0) {\r\n"
                "            $(\'.DrawCanvas\').before(\"<div class=\'DrawRectangle pagewidth\'><div class=\'DrawName\'>Draw Rectangle <button class=\'Draw-button Draw-button1 DrawRectangle_add_click\'>+</button> <button class=\'Draw-button Draw-button2 DrawRectangle_del_click\'>-</button> <button class=\'Draw-button Draw-button3 DrawRectangle_delall_click\'>delete</button></div><div class=\'Rectangles-father\'><table class=\'Rectangle\'><tr class=\'DrawNav\'><th>Num</th><th>Xstart</th><th>Ystart</th><th>Xend</th><th>Yend</th><th>Color</th><th>Width</th><th>Fill</th></tr><tr class=\'DrawNav\'><td>1</td><td><input type=\'text\' name=\'Rectangle_x1\' value=\'0\'></td><td><input type=\'text\' name=\'Rectangle_y1\' value=\'0\'></td><td><input type=\'text\' name=\'Rectangle_x2\' value=\'0\'></td><td><input type=\'text\' name=\'Rectangle_y2\' value=\'0\'></td><td><select name=\'Rectangle_Color\'><option value=\'0\'>WHITE</option><option value=\'1\'>BLACK</option><option class=\'show_ry\' value=\'2\'>\"+ ry_color + \"</option></select></td><td><select name=\'Rectangle_Width\'><option value=\'1\' selected>1</option><option value=\'2\'>2</option><option value=\'3\'>3</option><option value=\'4\'>4</option><option value=\'5\'>5</option><option value=\'6\'>6</option><option value=\'7\'>7</option><option value=\'8\'>8</option></select></td><td><select name=\'Rectangle_Fill\'><option value=\'1\' selected>EMPTY</option><option value=\'2\'>FULL</option></select></td></tr></table></div></div>\");\r\n"
                "            $(\'.DrawRectangle\').show();\r\n"
                "            DrawIfShow[2][1] = 1;\r\n"
                "        }\r\n"
                "    });\r\n"
                "    $(\'.DrawCircle-js\').click(function () {\r\n"
                "        consoledebug(\'DrawCircle\');\r\n"
                "        showDrawCanvas();\r\n"
                "        if (DrawIfShow[3][1] == 0) {\r\n"
                "            $(\'.DrawCanvas\').before(\"<div class=\'DrawCircle pagewidth\'><div class=\'DrawName\'>Draw Circle <button class=\'Draw-button Draw-button1 DrawCircle_add_click\'>+</button> <button class=\'Draw-button Draw-button2 DrawCircle_del_click\'>-</button> <button class=\'Draw-button Draw-button3 DrawCircle_delall_click\'>delete</button></div><div class=\'Circles-father\'><table class=\'Circle\'><tr class=\'DrawNav\'><th>Num</th><th>XCenter</th><th>YCenter</th><th>Radius</th><th>Color</th><th>Width</th><th>Fill</th></tr><tr class=\'DrawNav\'><td>1</td><td><input type=\'text\' name=\'Circle_x\' value=\'0\'></td><td><input type=\'text\' name=\'Circle_y\' value=\'0\'></td><td><input type=\'text\' name=\'Circle_r\' value=\'0\'></td><td><select name=\'Circle_Color\'><option value=\'0\'>WHITE</option><option value=\'1\'>BLACK</option><option class=\'show_ry\' value=\'2\'>\"+ ry_color + \"</option></select></td><td><select name=\'Circle_Width\'><option value=\'1\' selected>1</option><option value=\'2\'>2</option><option value=\'3\'>3</option><option value=\'4\'>4</option><option value=\'5\'>5</option><option value=\'6\'>6</option><option value=\'7\'>7</option><option value=\'8\'>8</option></select></td><td><select name=\'Circle_Fill\'><option value=\'1\' selected>EMPTY</option><option value=\'2\'>FULL</option></select></td></tr></table></div></div>\");\r\n"
                "            $(\'.DrawCircle\').show();\r\n"
                "            DrawIfShow[3][1] = 1;\r\n"
                "        }\r\n"
                "    });\r\n"
                "    $(\'.DrawString-js\').click(function () {\r\n"
                "        consoledebug(\'DrawString\');\r\n"
                "        showDrawCanvas();\r\n"
                "        if (DrawIfShow[4][1] == 0) {\r\n"
                "            $(\'.DrawCanvas\').before(\"<div class=\'DrawString pagewidth\'><div class=\'DrawName\'>Draw String <button class=\'Draw-button Draw-button1 DrawString_add_click\'>+</button> <button class=\'Draw-button Draw-button2 DrawString_del_click\'>-</button> <button class=\'Draw-button Draw-button3 DrawString_delall_click\'>delete</button></div><div class=\'Strings-father\'><table class=\'String\'><tr class=\'DrawNav\'><th>Num</th><th>X</th><th>Y</th><th>String</th><th>size</th><th>Color</th></tr><tr class=\'DrawNav\'><td>1</td><td><input type=\'text\' name=\'String_x\' value=\'0\'></td><td><input type=\'text\' name=\'String_y\' value=\'0\'></td><td><input type=\'text\' name=\'String_String\' value=\'s\'></td><td><select name=\'String_Fontsize\'><option value=\'10\'>10px</option><option value=\'20\'>20px</option><option value=\'30\'>30px</option><option value=\'40\'>40px</option><option value=\'50\'>50px</option></select></td><td><select name=\'String_fontColor\'><option value=\'0\'>WHITE</option><option value=\'1\'>BLACK</option><option class=\'show_ry\' value=\'2\'>\"+ ry_color + \"</option></select></td></tr></table></div></div>\");\r\n"
                "            $(\'.DrawString\').show();\r\n"
                "            DrawIfShow[4][1] = 1;\r\n"
                "        }\r\n"
                "    });\r\n"
                "    $(\'.ShowPic-js\').click(function () {\r\n"
                "        consoledebug(\'Show Picture\');\r\n"
                "        showDrawCanvas();\r\n"
                "        if (DrawIfShow[5][1] == 0) {\r\n"
                "            $(\'.DrawCanvas\').before(\"<div class=\'ShowPic pagewidth\'><div class=\'DrawName\'>Show Picture <button class=\'Draw-button Draw-button1 ShowPic_add_click\'>+</button> <button class=\'Draw-button Draw-button2 ShowPic_del_click\'>-</button> <button class=\'Draw-button Draw-button3 ShowPic_delall_click\'>delete</button></div><div class=\'pic-father\'><table class=\'pic\'><tr class=\'DrawNav\'><th>Num</th><th>Xstart</th><th>Ystart</th><th>image</th><th>mode1</th><th>mode2</th><th>mode3</th><th>mode4</th></tr><tr class=\'DrawNav\'><td>1</td><td><input type=\'text\' name=\'img_x\' value=\'0\'></td><td><input type=\'text\' name=\'img_y\' value=\'0\'></td><td><div class=\'image-button\'><input type=\'file\' class=\'input-file preview_img\'> <span class=\'tip\'>upload image</span></div></td><td><button class=\'image-button imagemode-js\' value=\'0\'>Level: mono</button></td><td><button class=\'image-button imagemode-js\' value=\'1\'>Level: color</button></td><td><button class=\'image-button imagemode-js\' value=\'2\'>Dithering: mono</button></td><td><button class=\'image-button imagemode-js\' value=\'3\'>Dithering: color</button></td></tr></table></div></div>\");\r\n"
                "            $(\'.ShowPic\').show();\r\n"
                "            DrawIfShow[5][1] = 1;\r\n"
                "            $(\'.DrawCanvas\').after(\"<div class=\'DrawCanvas2\' style=\'width:\" + canvasWidth + \'px height=\' + canvasHeight + \"px;\'><canvas class=\'epdCanvas\' id=\'epdCanvas2\' width=\" + canvasWidth + \' height=\' + canvasHeight + \"></canvas></div>\");\r\n"
                "        }\r\n"
                "    });  \r\n"
                "});\r\n"
                "function tableadd(tableclass, add_click, del_click) {\r\n"
                "    var num = $(tableclass).find(\'tr\').length;\r\n"
                "    consoledebug(add_click + \'=\' + num);\r\n"
                "    var content = \"<tr class=\'DrawNav\'><td>\" + num + \"</td>\";\r\n"
                "    if (add_click == \'DrawPoint_add_click\') {\r\n"
                "        content += \"<td><input type=\'text\' name=\'Point_x\' value=\'0\'></td><td><input type=\'text\' name=\'Point_y\' value=\'0\'></td><td><select name=\'Point_Color\'><option value=\'0\'>WHITE</option><option value=\'1\'>BLACK</option><option class=\'show_ry\' value=\'2\'>\"+ ry_color + \"</option></select></td><td><select name=\'Point_Pixel\'><option value=\'1\' selected>1</option><option value=\'2\'>2</option><option value=\'3\'>3</option><option value=\'4\'>4</option><option value=\'5\'>5</option><option value=\'6\'>6</option><option value=\'7\'>7</option><option value=\'8\'>8</option></select></td></tr>\";\r\n"
                "    } else if (add_click == \'DrawLine_add_click\') {\r\n"
                "        content += \"<td><input type=\'text\' name=\'Line_x1\' value=\'0\'></td><td><input type=\'text\' name=\'Line_y1\' value=\'0\'></td><td><input type=\'text\' name=\'Line_x2\' value=\'0\'></td><td><input type=\'text\' name=\'Line_y2\' value=\'0\'></td><td><select name=\'Line_Color\'><option value=\'0\'>WHITE</option><option value=\'1\'>BLACK</option><option class=\'show_ry\' value=\'2\'>\"+ ry_color + \"</option></select></td><td><select name=\'Line_Width\'><option value=\'1\' selected>1</option><option value=\'2\'>2</option><option value=\'3\'>3</option><option value=\'4\'>4</option><option value=\'5\'>5</option><option value=\'6\'>6</option><option value=\'7\'>7</option><option value=\'8\'>8</option></select></td><td><select name=\'Line_Style\'><option value=\'1\' selected=\'selected\'>SOLID</option><option value=\'2\'>DOTTED</option></select></td></tr>\";\r\n"
                "    } else if (add_click == \'DrawRectangle_add_click\') {\r\n"
                "        content += \"<td><input type=\'text\' name=\'Rectangle_x1\' value=\'0\'></td><td><input type=\'text\' name=\'Rectangle_y1\' value=\'0\'></td><td><input type=\'text\' name=\'Rectangle_x2\' value=\'0\'></td><td><input type=\'text\' name=\'Rectangle_y2\' value=\'0\'></td><td><select name=\'Rectangle_Color\'><option value=\'0\'>WHITE</option><option value=\'1\'>BLACK</option><option class=\'show_ry\' value=\'2\'>\"+ ry_color + \"</option></select></td><td><select name=\'Rectangle_Width\'><option value=\'1\' selected>1</option><option value=\'2\'>2</option><option value=\'3\'>3</option><option value=\'4\'>4</option><option value=\'5\'>5</option><option value=\'6\'>6</option><option value=\'7\'>7</option><option value=\'8\'>8</option></select></td><td><select name=\'Rectangle_Fill\'><option value=\'1\' selected>EMPTY</option><option value=\'2\'>FULL</option></select></td></tr>\";\r\n"
                "    } else if (add_click == \'DrawCircle_add_click\') {\r\n"
                "        content += \"<td><input type=\'text\' name=\'Circle_x\' value=\'0\'></td><td><input type=\'text\' name=\'Circle_y\' value=\'0\'></td><td><input type=\'text\' name=\'Circle_r\' value=\'0\'></td><td><select name=\'Circle_Color\'><option value=\'0\'>WHITE</option><option value=\'1\'>BLACK</option><option class=\'show_ry\' value=\'2\'>\"+ ry_color + \"</option></select></td><td><select name=\'Circle_Width\'><option value=\'1\' selected>1</option><option value=\'2\'>2</option><option value=\'3\'>3</option><option value=\'4\'>4</option><option value=\'5\'>5</option><option value=\'6\'>6</option><option value=\'7\'>7</option><option value=\'8\'>8</option></select></td><td><select name=\'Circle_Fill\'><option value=\'1\' selected>EMPTY</option><option value=\'2\'>FULL</option></select></td></tr>\";\r\n"
                "    } else if (add_click == \'DrawString_add_click\') {\r\n"
                "        content += \"<td><input type=\'text\' name=\'String_x\' value=\'0\'></td><td><input type=\'text\' name=\'String_y\' value=\'0\'></td><td><input type=\'text\' name=\'String_String\' value=\'s\'></td><td><select name=\'String_Fontsize\'><option value=\'10\'>10px</option><option value=\'20\'>20px</option><option value=\'30\'>30px</option><option value=\'40\'>40px</option><option value=\'50\'>50px</option></select></td><td><select name=\'String_fontColor\'><option value=\'0\'>WHITE</option><option value=\'1\'>BLACK</option><option class=\'show_ry\' value=\'2\'>\"+ ry_color + \"</option></select></td></tr>\";\r\n"
                "    } else if (add_click == \'ShowPic_add_click\') {\r\n"
                "        content += \"<td><input type=\'text\' name=\'img_x\' value=\'0\'></td><td><input type=\'text\' name=\'img_y\' value=\'0\'></td><td><div class=\'image-button\'><input type=\'file\' class=\'input-file preview_img\'> <span class=\'tip\'>upload image</span></div></td><td><button class=\'image-button imagemode-js\' value=\'0\'>Level: mono</button></td><td><button class=\'image-button imagemode-js\' value=\'1\'>Level: color</button></td><td><button class=\'image-button imagemode-js\' value=\'2\'>Dithering: mono</button></td><td><button class=\'image-button imagemode-js\' value=\'3\'>Dithering: color</button></td></tr>\";\r\n"
                "    } else {\r\n"
                "        consoledebug(\"none\");\r\n"
                "    }\r\n"
                "    $(tableclass).append(content);\r\n"
                "    hasRed(epdnum);\r\n"
                "    $(del_click).css({ \'display\': \'inline\' });\r\n"
                "}\r\n"
                "function tabledel(tableclass, del_click) {\r\n"
                "    consoledebug(del_click + \'num = \' + ($(tableclass).find(\'tr\').length - 2));\r\n"
                "    var len = $(tableclass).find(\'tr\').length;\r\n"
                "    if (len > 2) {\r\n"
                "        $(tableclass).find(\'tr\').eq(-1).remove();\r\n"
                "    }\r\n"
                "}\r\n"
                "function tabledelall(divclass, delall_click) {\r\n"
                "    consoledebug(delall_click);\r\n"
                "    $(divclass).remove();\r\n"
                "    if (delall_click == \'DrawPoint_delall_click\') {\r\n"
                "        DrawIfShow[0][1] = 0;\r\n"
                "    } else if (delall_click == \'DrawLine_delall_click\') {\r\n"
                "        DrawIfShow[1][1] = 0; \r\n"
                "    } else if (delall_click == \'DrawRectangle_delall_click\') {\r\n"
                "        DrawIfShow[2][1] = 0; \r\n"
                "    } else if (delall_click == \'DrawCircle_delall_click\') {\r\n"
                "        DrawIfShow[3][1] = 0; \r\n"
                "    } else if (delall_click == \'DrawString_delall_click\') {\r\n"
                "        DrawIfShow[4][1] = 0; \r\n"
                "    } else if (delall_click == \'ShowPic_delall_click\') {\r\n"
                "        DrawIfShow[5][1] = 0; \r\n"
                "    } else {\r\n"
                "        consoledebug(\"none\");\r\n"
                "    }\r\n"
                "}\r\n"
                "/*****************************/\r\n"
                "$(document).on(\'click\', \'.DrawPoint_add_click\', function () {\r\n"
                "    tableadd(\'.Point\', \'DrawPoint_add_click\', \'.DrawPoint_del_click\');\r\n"
                "});\r\n"
                "$(document).on(\'click\', \'.DrawPoint_del_click\', function () {\r\n"
                "    tabledel(\'.Point\', \'.DrawPoint_del_click\');\r\n"
                "});\r\n"
                "$(document).on(\'click\', \'.DrawPoint_delall_click\', function () {\r\n"
                "    tabledelall(\'.DrawPoint\', \'DrawPoint_delall_click\');\r\n"
                "});\r\n"
                "/******************************/\r\n"
                "$(document).on(\'click\', \'.DrawLine_add_click\', function () {\r\n"
                "    tableadd(\'.Line\', \'DrawLine_add_click\', \'.DrawLine_del_click\');\r\n"
                "});\r\n"
                "$(document).on(\'click\', \'.DrawLine_del_click\', function () {\r\n"
                "    tabledel(\'.Line\', \'DrawLine_del_click\');\r\n"
                "});\r\n"
                "$(document).on(\'click\', \'.DrawLine_delall_click\', function () {\r\n"
                "    tabledelall(\'.DrawLine\', \'DrawLine_delall_click\');\r\n"
                "});\r\n"
                "/******************************/\r\n"
                "$(document).on(\'click\', \'.DrawRectangle_add_click\', function () {\r\n"
                "    tableadd(\'.Rectangle\', \'DrawRectangle_add_click\', \'.DrawRectangle_del_click\');\r\n"
                "});\r\n"
                "$(document).on(\'click\', \'.DrawRectangle_del_click\', function () {\r\n"
                "    tabledel(\'.Rectangle\', \'DrawRectangle_del_click\');\r\n"
                "});\r\n"
                "$(document).on(\'click\', \'.DrawRectangle_delall_click\', function () {\r\n"
                "    tabledelall(\'.DrawRectangle\', \'DrawRectangle_delall_click\');\r\n"
                "});\r\n"
                "/******************************/\r\n"
                "$(document).on(\'click\', \'.DrawCircle_add_click\', function () {\r\n"
                "    tableadd(\'.Circle\', \'DrawCircle_add_click\', \'.DrawCircle_del_click\');\r\n"
                "});\r\n"
                "$(document).on(\'click\', \'.DrawCircle_del_click\', function () {\r\n"
                "    tabledel(\'.Circle\', \'DrawCircle_del_click\');\r\n"
                "});\r\n"
                "$(document).on(\'click\', \'.DrawCircle_delall_click\', function () {\r\n"
                "    tabledelall(\'.DrawCircle\', \'DrawCircle_delall_click\');\r\n"
                "});\r\n"
                "/******************************/\r\n"
                "$(document).on(\'click\', \'.DrawString_add_click\', function () {\r\n"
                "    tableadd(\'.String\', \'DrawString_add_click\', \'.DrawString_del_click\');\r\n"
                "});\r\n"
                "$(document).on(\'click\', \'.DrawString_del_click\', function () {\r\n"
                "    tabledel(\'.String\', \'DrawString_del_click\');\r\n"
                "});\r\n"
                "$(document).on(\'click\', \'.DrawString_delall_click\', function () {\r\n"
                "    tabledelall(\'.DrawString\', \'DrawString_delall_click\');\r\n"
                "});\r\n"
                "/* */\r\n"
                "$(document).on(\'click\', \'.ShowPic_add_click\', function () {\r\n"
                "    tableadd(\'.pic\', \'ShowPic_add_click\', \'.ShowPic_del_click\');\r\n"
                "});\r\n"
                "$(document).on(\'click\', \'.ShowPic_del_click\', function () {\r\n"
                "    tabledel(\'.pic\', \'ShowPic_del_click\');\r\n"
                "});\r\n"
                "$(document).on(\'click\', \'.ShowPic_delall_click\', function () {\r\n"
                "    tabledelall(\'.ShowPic\', \'ShowPic_delall_click\');\r\n"
                "});\r\n"
                "var imgURL = new Array;\r\n"
                "$(document).on(\'change\',\'.preview_img\',function(event){\r\n"
                "    var numname = $(this).parents(\'tr\').find(\'td\').eq(0).html();\r\n"
                "    consoledebug(numname);\r\n"
                "    var fileList = event.target.files[0];\r\n"
                "    consoledebug(fileList.name);\r\n"
                "    $(this).parents(\'tr\').find(\'span\').empty();\r\n"
                "    $(this).parents(\'tr\').find(\'span\').append(fileList.name);\r\n"
                "    var reader = new FileReader();\r\n"
                "    reader.readAsDataURL(fileList);\r\n"
                "    reader.onload = function (e) {\r\n"
                "        imgURL[numname - 1] = reader.result;\r\n"
                "        console.info(imgURL[numname - 1]);\r\n"
                "        drawing();\r\n"
                "    }\r\n"
                "});\r\n"
                "var curPal;\r\n"
                "var source;\r\n"
                "var dX, dY, dW, dH, sW, sH;\r\n"
                "function getVal(p, i) {\r\n"
                "    if ((p.data[i] == 0x00) && (p.data[i + 1] == 0x00)) return 0;\r\n"
                "    if ((p.data[i] == 0xFF) && (p.data[i + 1] == 0xFF)) return 1;\r\n"
                "    if ((p.data[i] == 0x7F) && (p.data[i + 1] == 0x7F)) return 2;\r\n"
                "    return 3;\r\n"
                "}\r\n"
                "function setVal(p, i, c) {\r\n"
                "    p.data[i] = curPal[c][0];\r\n"
                "    p.data[i + 1] = curPal[c][1];\r\n"
                "    p.data[i + 2] = curPal[c][2];\r\n"
                "    p.data[i + 3] = 255;\r\n"
                "}\r\n"
                "function addVal(c, r, g, b, k) {\r\n"
                "    return [c[0] + (r * k) / 32, c[1] + (g * k) / 32, c[2] + (b * k) / 32];\r\n"
                "}\r\n"
                "function getErr(r, g, b, stdCol) {\r\n"
                "    r -= stdCol[0];\r\n"
                "    g -= stdCol[1];\r\n"
                "    b -= stdCol[2];\r\n"
                "    return r * r + g * g + b * b;\r\n"
                "}\r\n"
                "function getNear(r, g, b) {\r\n"
                "    var ind = 0;\r\n"
                "    var err = getErr(r, g, b, curPal[0]);\r\n"
                "    for (var i = 1; i < curPal.length; i++) {\r\n"
                "        var cur = getErr(r, g, b, curPal[i]);\r\n"
                "        if (cur < err) { err = cur; ind = i; }\r\n"
                "    }\r\n"
                "    return ind;\r\n"
                "}\r\n"
                "var imgpDst = new Array;\r\n"
                "$(document).on(\'click\',\'.imagemode-js\',function(){\r\n"
                "    var numname = $(this).parents(\'tr\').find(\'td\').eq(0).html();\r\n" 
                "    var img= new Image();\r\n"
                "    img.src = imgURL[numname - 1]; \r\n"
                "    consoledebug(\'img.width = \' + img.width + \',img.height = \' + img.height);\r\n"
                "    if (img.width == 0) {\r\n"
                "        alert(\'First upload image num：\' + numname);\r\n"
                "        return;\r\n"
                "    }\r\n"
                "    if (img.width < 3 || img.height < 3) {\r\n"
                "        alert(\'Image is too small, please Reselect image\');\r\n"
                "        return;\r\n"
                "    }\r\n"
                "    \r\n"
                "    var source = document.getElementById(\'epdCanvas\');\r\n"
                "    var canvas = document.getElementById(\'epdCanvas2\');\r\n"
                "    var x0 = x = $(\'.pic\').find(\'.DrawNav\').find(\'input\').eq(3 * (numname - 1)).val();\r\n"
                "    var y0 = y = $(\'.pic\').find(\'.DrawNav\').find(\'input\').eq(3 * (numname - 1) + 1).val();\r\n"
                "    consoledebug(\'x = \' + x + \',y = \' + y);\r\n"
                "    dX = 0;\r\n"
                "    dY = 0;\r\n"
                "    sW = img.width;\r\n"
                "    sH = img.height;\r\n"
                "    dW = img.width;\r\n"
                "    dH = img.height;\r\n"
                "    console.log(\'dX = \' + dX);\r\n"
                "    console.log(\'dY = \' + dY);\r\n"
                "    console.log(\'dW = \' + dW);\r\n"
                "    console.log(\'dH = \' + dH);\r\n"
                "    var pSrc = canvas.getContext(\'2d\').getImageData(x, y, sW, sH);\r\n"
                "    var pDst = source.getContext(\'2d\').getImageData(x, y, dW, dH);\r\n"  
                "    var isLvl = (this.value & 0x02) == 0?1:0;\r\n"
                "    var isRed = this.value & 0x01;\r\n"
                "    consoledebug(\'isLvl = \' + isLvl + \',isRed = \' + isRed);\r\n"
                "    consoledebug(\'epdArr[epdnum][4] = \' + epdArr[epdnum][4]);\r\n"
                "    var palInd =  epdArr[epdnum][4];\r\n"
                "    if (isRed && ((palInd & 1) == 0)) {\r\n"
                "        alert(\'This white-black display\');\r\n"
                "        return;\r\n"
                "    }\r\n"
                "    if (!isRed) palInd = palInd & 0xFE;\r\n"
                "    console.log(\'palInd  = \' + palInd);\r\n"
                "    curPal = palArr[palInd];\r\n"
                "    var index = 0;\r\n"
                "    if (isLvl) {\r\n"
                "        consoledebug(\'isLvl\');\r\n"
                "        for (var j = 0; j < dH; j++) {\r\n"
                "            var y = dY + j;\r\n"
                "            if ((y < 0) || (y >= sH)) {\r\n"
                "                for (var i = 0; i < dW; i++ , index += 4) \r\n"
                "                    setVal(pDst, index, (i + j) % 2 == 0 ? 1 : 0);\r\n"
                "                continue;\r\n"
                "            }\r\n"
                "            for (var i = 0; i < dW; i++) {\r\n"
                "                var x = dX + i;\r\n"
                "                if ((x < 0) || (x >= sW)) {\r\n"
                "                    setVal(pDst, index, (i + j) % 2 == 0 ? 1 : 0);\r\n"
                "                    index += 4;\r\n"
                "                    continue;\r\n"
                "                }\r\n"
                "                var pos = (y * sW + x) * 4;\r\n"
                "                setVal(pDst, index, getNear(pSrc.data[pos], pSrc.data[pos + 1], pSrc.data[pos + 2]));\r\n"
                "                index += 4;\r\n"
                "            }\r\n"
                "        }\r\n"
                "    } else {\r\n"
                "        consoledebug(\'isRed\');\r\n"
                "        var aInd = 0;\r\n"
                "        var bInd = 1;\r\n"
                "        var errArr = new Array(2);\r\n"
                "        errArr[0] = new Array(dW);\r\n"
                "        errArr[1] = new Array(dW);\r\n"
                "        for (var i = 0; i < dW; i++)\r\n"
                "            errArr[bInd][i] = [0, 0, 0];\r\n"
                "        for (var j = 0; j < dH; j++) {\r\n"
                "            var y = dY + j;\r\n"
                "            if ((y < 0) || (y >= sH)) {\r\n"
                "                for (var i = 0; i < dW; i++ , index += 4)\r\n"
                "                    setVal(pDst, index, (i + j) % 2 == 0 ? 1 : 0);\r\n"
                "                continue;\r\n"
                "            }\r\n"
                "            aInd = ((bInd = aInd) + 1) & 1;\r\n"
                "            for (var i = 0; i < dW; i++)errArr[bInd][i] = [0, 0, 0];\r\n"
                "            for (var i = 0; i < dW; i++) {\r\n"
                "                var x = dX + i;\r\n"
                "                if ((x < 0) || (x >= sW)) {\r\n"
                "                    setVal(pDst, index, (i + j) % 2 == 0 ? 1 : 0);\r\n"
                "                    index += 4;\r\n"
                "                    continue;\r\n"
                "                }\r\n"
                "                var pos = (y * sW + x) * 4;\r\n"
                "                var old = errArr[aInd][i];\r\n"
                "                var r = pSrc.data[pos] + old[0];\r\n"
                "                var g = pSrc.data[pos + 1] + old[1];\r\n"
                "                var b = pSrc.data[pos + 2] + old[2];\r\n"
                "                var colVal = curPal[getNear(r, g, b)];\r\n"
                "                pDst.data[index++] = colVal[0];\r\n"
                "                pDst.data[index++] = colVal[1];\r\n"
                "                pDst.data[index++] = colVal[2];\r\n"
                "                pDst.data[index++] = 255;\r\n"
                "                r = (r - colVal[0]);\r\n"
                "                g = (g - colVal[1]);\r\n"
                "                b = (b - colVal[2]);\r\n"
                "                if (i == 0) {\r\n"
                "                    errArr[bInd][i] = addVal(errArr[bInd][i], r, g, b, 7.0);\r\n"
                "                    errArr[bInd][i + 1] = addVal(errArr[bInd][i + 1], r, g, b, 2.0);\r\n"
                "                    errArr[aInd][i + 1] = addVal(errArr[aInd][i + 1], r, g, b, 7.0);\r\n"
                "                } else if (i == dW - 1) {\r\n"
                "                    errArr[bInd][i - 1] = addVal(errArr[bInd][i - 1], r, g, b, 7.0);\r\n"
                "                    errArr[bInd][i] = addVal(errArr[bInd][i], r, g, b, 9.0);\r\n"
                "                } else {\r\n"
                "                    errArr[bInd][i - 1] = addVal(errArr[bInd][i - 1], r, g, b, 3.0);\r\n"
                "                    errArr[bInd][i] = addVal(errArr[bInd][i], r, g, b, 5.0);\r\n"
                "                    errArr[bInd][i + 1] = addVal(errArr[bInd][i + 1], r, g, b, 1.0);\r\n"
                "                    errArr[aInd][i + 1] = addVal(errArr[aInd][i + 1], r, g, b, 7.0);\r\n"
                "                }\r\n"
                "            }\r\n"
                "        }\r\n"
                "    }\r\n"
                "    // canvas.getContext(\'2d\').putImageData(pDst, x0, y0);\r\n"
                "    imgpDst[numname - 1] = pDst;\r\n"
                "    source.getContext(\'2d\').putImageData(pDst, x0, y0);\r\n"
                "});\r\n"
                "function drawing(){\r\n"
                "    var c = document.getElementById(\'epdCanvas\');\r\n"
                "    var cxt = c.getContext(\'2d\');\r\n"
                "    cxt.clearRect(0, 0, canvasWidth, canvasHeight);\r\n"
                "    var x, y, color, size;\r\n"
                "    if (DrawIfShow[0][1] == 1) {\r\n"
                "        var len = $(\"input[name=\'Point_x\']\").length;\r\n"
                "        consoledebug(\'Point len = \' + len);\r\n"
                "        for (var i = 0; i < len; i++) {\r\n"
                "            x = $(\'.Point\').find(\'.DrawNav\').find(\'input\').eq(2 * i).val();\r\n"
                "            y = $(\'.Point\').find(\'.DrawNav\').find(\'input\').eq(2 * i + 1).val();\r\n"
                "            color = $(\'.Point\').find(\'.DrawNav\').find(\'option:selected\').eq(2 * i).val();\r\n"
                "            size = $(\'.Point\').find(\'.DrawNav\').find(\'option:selected\').eq(2 * i + 1).val();\r\n"
                "            cxt.fillStyle = (color == 0 ? \'#FFFFFF\' : (color == 1 ? \'#000000\' : \'#FF0000\'));\r\n"
                "            cxt.fillRect(x, y, size, size);\r\n"
                "        }\r\n"
                "    }\r\n"
                "    var x1, y1, x2, y2, color, size, style;\r\n"
                "    if (DrawIfShow[1][1] == 1) {\r\n"
                "        var len = $(\"input[name=\'Line_x1\']\").length;\r\n"
                "        consoledebug(\'Line len = \' + len);\r\n"
                "        for (var i = 0; i < len; i++) {\r\n"
                "            x1 = $(\'.Line\').find(\'.DrawNav\').find(\'input\').eq(4 * i).val();\r\n"
                "            y1 = $(\'.Line\').find(\'.DrawNav\').find(\'input\').eq(4 * i + 1).val();\r\n"
                "            x2 = $(\'.Line\').find(\'.DrawNav\').find(\'input\').eq(4 * i + 2).val();\r\n"
                "            y2 = $(\'.Line\').find(\'.DrawNav\').find(\'input\').eq(4 * i + 3).val();\r\n"
                "            color = $(\'.Line\').find(\'.DrawNav\').find(\'option:selected\').eq(3 * i).val();\r\n"
                "            size = $(\'.Line\').find(\'.DrawNav\').find(\'option:selected\').eq(3 * i + 1).val();\r\n"
                "            style = $(\'.Line\').find(\'.DrawNav\').find(\'option:selected\').eq(3 * i + 2).val();\r\n"
                "            cxt.beginPath();\r\n"
                "            cxt.strokeStyle = (color == 0 ? \'#FFFFFF\' : (color == 1 ? \'#000000\' : \'#FF0000\'));\r\n"
                "            cxt.lineWidth = size;\r\n"
                "            cxt.setLineDash(style == 1 ? [5, 0] : [5, 2]);\r\n"
                "            cxt.moveTo(x1, y1);\r\n"
                "            cxt.lineTo(x2, y2);\r\n"
                "            cxt.stroke();\r\n"
                "        }\r\n"
                "    }\r\n"
                "    var x1, y1, x2, y2, color, size, fill;\r\n"
                "    if (DrawIfShow[2][1] == 1) {\r\n"
                "        var len = $(\"input[name=\'Rectangle_x1\']\").length;\r\n"
                "        consoledebug(\'Rectangle len = \' + len);\r\n"
                "        for (var i = 0; i < len; i++) {\r\n"
                "            x1 = $(\'.Rectangle\').find(\'.DrawNav\').find(\'input\').eq(4 * i).val();\r\n"
                "            y1 = $(\'.Rectangle\').find(\'.DrawNav\').find(\'input\').eq(4 * i + 1).val();\r\n"
                "            x2 = $(\'.Rectangle\').find(\'.DrawNav\').find(\'input\').eq(4 * i + 2).val();\r\n"
                "            y2 = $(\'.Rectangle\').find(\'.DrawNav\').find(\'input\').eq(4 * i + 3).val();\r\n"
                "            color = $(\'.Rectangle\').find(\'.DrawNav\').find(\'option:selected\').eq(3 * i).val();\r\n"
                "            size = $(\'.Rectangle\').find(\'.DrawNav\').find(\'option:selected\').eq(3 * i + 1).val();\r\n"
                "            fill = $(\'.Rectangle\').find(\'.DrawNav\').find(\'option:selected\').eq(3 * i + 2).val();\r\n"
                "            if (x1 > x2) {\r\n"
                "                var x = x1;\r\n"
                "                x1 = x2;\r\n"
                "                x2 = x;\r\n"
                "            }\r\n"
                "            if (y1 > y2) {\r\n"
                "                var x = x1;\r\n"
                "                x1 = x2;\r\n"
                "                x2 = x;\r\n"
                "            }\r\n"
                "            if (fill == 1) {\r\n"
                "                cxt.beginPath();\r\n"
                "                cxt.lineWidth = size;\r\n"
                "                cxt.strokeStyle = (color == 0 ? \'#FFFFFF\' : (color == 1 ? \'#000000\' : \'#FF0000\'));\r\n"
                "                cxt.rect(x1, y1, x2 - x1, y2 - y1);\r\n"
                "                cxt.setLineDash([5, 0]);\r\n"
                "                cxt.stroke();\r\n"
                "            } else {\r\n"
                "                cxt.fillStyle = (color == 0 ? \'#FFFFFF\' : (color == 1 ? \'#000000\' : \'#FF0000\'));\r\n"
                "                cxt.fillRect(x1, y1, x2 - x1, y2 - y1);\r\n"
                "            }\r\n"
                "        }\r\n"
                "    }\r\n"
                "    var x, y, r, color, size, fill;\r\n"
                "    if (DrawIfShow[3][1] == 1) {\r\n"
                "        var len = $(\"input[name=\'Circle_x\']\").length;\r\n"
                "        consoledebug(\'Circle len = \' + len);\r\n"
                "        for (var i = 0; i < len; i++) {\r\n"
                "            x = $(\'.Circle\').find(\'.DrawNav\').find(\'input\').eq(3 * i).val();\r\n"
                "            y = $(\'.Circle\').find(\'.DrawNav\').find(\'input\').eq(3 * i + 1).val();\r\n"
                "            r = $(\'.Circle\').find(\'.DrawNav\').find(\'input\').eq(3 * i + 2).val();\r\n"
                "            color = $(\'.Circle\').find(\'.DrawNav\').find(\'option:selected\').eq(3 * i).val();\r\n"
                "            size = $(\'.Circle\').find(\'.DrawNav\').find(\'option:selected\').eq(3 * i + 1).val();\r\n"
                "            fill = $(\'.Circle\').find(\'.DrawNav\').find(\'option:selected\').eq(3 * i + 2).val();\r\n"
                "            cxt.beginPath();\r\n"
                "            cxt.lineWidth = size;\r\n"
                "            cxt.strokeStyle = (color == 0 ? \'#FFFFFF\' : (color == 1 ? \'#000000\' : \'#FF0000\'));\r\n"
                "            cxt.arc(x, y, r, 0, 360);\r\n"
                "            if (fill == 2) {\r\n"
                "                cxt.fillStyle = (color == 0 ? \'#FFFFFF\' : (color == 1 ? \'#000000\' : \'#FF0000\'));\r\n"
                "                cxt.fill();\r\n"
                "            }\r\n"
                "            cxt.stroke();\r\n"
                "        }\r\n"
                "    }\r\n"
                "    var x, y, str, size, fontcolor;\r\n"
                "    if (DrawIfShow[4][1] == 1) {\r\n"
                "        var len = $(\"input[name=\'String_x\']\").length;\r\n"
                "        consoledebug(\'String len = \' + len);\r\n"
                "        for (var i = 0; i < len; i++) {\r\n"
                "            x = $(\'.String\').find(\'.DrawNav\').find(\'input\').eq(3 * i).val();\r\n"
                "            y = $(\'.String\').find(\'.DrawNav\').find(\'input\').eq(3 * i + 1).val();\r\n"
                "            str = $(\'.String\').find(\'.DrawNav\').find(\'input\').eq(3 * i + 2).val();\r\n"
                "            size = $(\'.String\').find(\'.DrawNav\').find(\'option:selected\').eq(2 * i).val();\r\n"
                "            fontcolor = $(\'.String\').find(\'.DrawNav\').find(\'option:selected\').eq(2 * i + 1).val();\r\n"
                "            consoledebug(\'size = \' + size);\r\n"
                "            cxt.font = size + \'px Georgia\';\r\n"
                "            cxt.fillStyle = (fontcolor == 0 ? \'#FFFFFF\' : (fontcolor == 1 ? \'#000000\' : \'#FF0000\'));\r\n"
                "            cxt.fillText(str, x, y);\r\n"
                "        }\r\n"
                "    }\r\n"
                "    var x, y;\r\n"
                "    if (DrawIfShow[5][1] == 1) {\r\n"
                "        var c2 = document.getElementById(\'epdCanvas2\');\r\n"
                "        var cxt2 = c2.getContext(\'2d\');\r\n"
                "        cxt2.clearRect(0, 0, canvasWidth, canvasHeight);\r\n"
                "        var len = $(\"input[name=\'img_x\']\").length;\r\n"
                "        consoledebug(\'pic len = \' + len);\r\n"
                "        for (var i = 0; i < len; i++) {\r\n"
                "            x = $(\'.pic\').find(\'.DrawNav\').find(\'input\').eq(3 * i).val();\r\n"
                "            y = $(\'.pic\').find(\'.DrawNav\').find(\'input\').eq(3 * i + 1).val();\r\n"
                "            var img= new Image();\r\n"
                "            img.src = imgURL[i]; \r\n"
                "            consoledebug(\'pic:\' + i + \'x:\' + x + \'y:\' + y + \' -img.src = \' + img.src);  \r\n"
                "            \r\n"
                "            cxt2.drawImage(img, x, y, img.width, img.height);\r\n"
                "            \r\n"
                "            cxt.putImageData(imgpDst[len - 1], x, y);\r\n"
                "        }\r\n"
                "    }\r\n"
                "}\r\n"
                "$(document).on(\'click\', \'input\', function() {\r\n"
                "    drawing();\r\n"
                "})\r\n"
                "$(document).on(\'blur\', \'input\', function() {\r\n"
                "    drawing();\r\n"
                "})\r\n"
                "$(document).on(\'click\', \'select\', function () {\r\n"
                "    drawing();\r\n"
                "});\r\n"
                "$(document).on(\'click\', \'.uploadimage_button\', function () {\r\n"
                "    var imagex = epdArr[epdnum][1];\r\n"
                "    var imagey = epdArr[epdnum][2];\r\n"
                "    var c = document.getElementById(\'epdCanvas\');\r\n"
                "    var data = c.getContext(\'2d\').getImageData(0, 0, imagex, imagey).data;\r\n"
                "    // console.log(data);\r\n"
                "    //Convert rgb888 image to black and white with 1bit = 1pixel\r\n"
                "    var blackimgbit = new Array(imagex * imagey);\r\n"
                "    var ryimgbit = new Array(imagex * imagey);\r\n"
                "    for (var i = 0; i < imagex * imagey; i++) {\r\n"
                "        blackimgbit[i] = 1;\r\n"
                "        ryimgbit[i] = 1;\r\n"
                "    }    \r\n"
                "     for (var i = 0; i < imagex * imagey; i++) {\r\n"
                "    // for (var i = 0; i < 240; i++) {\r\n"
                "        if (data[4 * i + 3] != 0) {\r\n"
                "            if (data[4 * i] == 0 && data[4 * i + 1] == 0 && data[4 * i + 2] == 0) {// black\r\n"
                "                blackimgbit[i] = 0;\r\n"
                "            }else if(!(data[4 * i] == 255 && data[4 * i + 1] == 255 && data[4 * i + 2] == 255)){// Non-white, red or yellow\r\n"
                "                ryimgbit[i] = 0;\r\n"
                "            }\r\n"
                "        }\r\n"
                "    }\r\n"
                "    //Convert 4bit to characters, 0000-1111 to a-p for easy sending\r\n"
                "    var xstr = ((imagex % 4 == 0)? (imagex / 4): (imagex / 4 + 1));\r\n"
                "    var ystr = imagey;\r\n"
                "    var bimg = new Array(xstr * ystr);\r\n"
                "    var ryimg = new Array(xstr * ystr);\r\n"
                "    for (var i = 0; i < xstr * ystr; i++) {\r\n"
                "        bimg[i] = 0x00;\r\n"
                "        ryimg[i] = 0x00;\r\n"
                "    }    \r\n"
                "    var x = 0, j = 0;\r\n"
                "    bimgMsg = \'\';\r\n"
                "    ryimgMsg = \'\';\r\n"
                "    for (var i = 0; i < imagex * imagey; i++) {\r\n"
                "        // for (var i = 0; i < 240; i++) {\r\n"
                "        bimg[x] +=   blackimgbit[i]<< (3 - j);\r\n"
                "        ryimg[x] +=  ryimgbit[i]<< (3 - j);\r\n"
                "        j = j + 1;\r\n"
                "        if(j == 4){\r\n"
                "            j = 0;\r\n"
                "            bimgMsg += String.fromCharCode(bimg[x] + 97);\r\n"
                "            ryimgMsg += String.fromCharCode(ryimg[x] + 97);\r\n"
                "            x++;\r\n"
                "        }\r\n"
                "    }\r\n"
                "    bimgm1s1m2s2=\'\';\r\n"
                "    ryimgm1s1m2s2=\'\';\r\n"
                "    for(var i = 0; i < 492; i++){\r\n"
                "        bimgm1s1m2s2 += bimgMsg.substr(i * 326, 162);\r\n"
                "        ryimgm1s1m2s2 += ryimgMsg.substr(i * 326, 162);\r\n"
                "    }\r\n"
                "    for(var i = 0; i < 492; i++){\r\n"
                "        bimgm1s1m2s2 += bimgMsg.substr(i * 326 + 162, 164);\r\n"
                "        ryimgm1s1m2s2 += ryimgMsg.substr(i * 326 + 162, 164);\r\n"
                "    }\r\n"
                "    for(var i = 492; i < 984; i++){\r\n"
                "        bimgm1s1m2s2 += bimgMsg.substr(i * 326, 162);\r\n"
                "        ryimgm1s1m2s2 += ryimgMsg.substr(i * 326, 162);\r\n"
                "    }\r\n"
                "    for(var i = 492; i < 984; i++){\r\n"
                "        bimgm1s1m2s2 += bimgMsg.substr(i * 326 + 162, 164);\r\n"
                "        ryimgm1s1m2s2 += ryimgMsg.substr(i * 326 + 162, 164);\r\n"
                "    }\r\n"
                "    //Send 30,000 characters at a time, and more may fail\r\n"
                "    var Btime = Math.ceil(bimgm1s1m2s2.length/30000);//Rounded up\r\n"
                "    var RYtime = Math.ceil(ryimgm1s1m2s2.length/30000);\r\n"
                "    // consoledebug(\'alltime = \' + Btime);\r\n"
                "    \r\n"
                "    var bnext =  0, rynext = 0;\r\n"
                "    var show = 0;\r\n"
                "    // consoledebug(\'bimgm1s1m2s2 = \' + bimgm1s1m2s2.substr(bnext*30000,30000));\r\n"
                "    var url = \'http://\' + document.getElementById(\'DeviceIP\').value + \'/\';\r\n"
                "    xmlHttp = new XMLHttpRequest();\r\n"
                "    consoledebug(\'send EPD\');\r\n"
                "    xmlHttp.open(\'POST\', url + \'EPD\', true); \r\n"
                "    xmlHttp.send(epdArr[epdnum][0]);\r\n"
                "    xmlHttp.onload = xmlHttp.onerror = function () {\r\n"
                "consoledebug(xmlHttp.status);"
                "        //black\r\n"
                "        if (xmlHttp.status==200  && bnext<Btime) {\r\n"
                "            consoledebug(\'LOAD A:\' + bnext + \', len = \' + bimgm1s1m2s2.substr(bnext*30000,30000).length)\r\n"
                "            xmlHttp.open(\'POST\', url + \'LOADA\', true); \r\n"
                "            xmlHttp.send(bimgm1s1m2s2.substr(bnext*30000,30000));\r\n"
                "        }\r\n"
                "        bnext++;\r\n"
                "consoledebug(bnext);\r\n"
                "        //red\r\n"
                "        if (xmlHttp.status==200 && bnext>Btime && epdArr[epdnum][3]!=0 && rynext<RYtime) {\r\n"
                "            consoledebug(\'LOAD B:\' + rynext + \', len = \' + ryimgm1s1m2s2.substr(rynext*30000,30000).length)\r\n"
                "            xmlHttp.open(\'POST\', url + \'LOADB\', true); \r\n"
                "            xmlHttp.send(ryimgm1s1m2s2.substr(rynext*30000,30000));\r\n"
                "        }\r\n"
                "        if(bnext>Btime  && epdArr[epdnum][0]!=0)// r/b/w\r\n"
                "            rynext++;\r\n"
                "        //SHOW\r\n"
                "        if (xmlHttp.status==200 && epdArr[epdnum][3]==0 && bnext>Btime && show==0) {\r\n"
                "            consoledebug(\'SHOW\');\r\n"
                "            xmlHttp.open(\'POST\', url + \'SHOW\', true); \r\n"
                "            xmlHttp.send(epdArr[epdnum][0]);\r\n"
                "            show = 1;\r\n"
                "        }else if(xmlHttp.status==200 && rynext>RYtime && show==0){\r\n"
                "            consoledebug(\'SHOW\');\r\n"
                "            xmlHttp.open(\'POST\', url + \'SHOW\', true); \r\n"
                "            xmlHttp.send(epdArr[epdnum][0]);\r\n"
                "            show = 1;\r\n"
                "        }\r\n"
                "    };\r\n"
                "});"
               );
}
